create database citely;
create table citations (
	"address"			TEXT,	
	"annote"			TEXT,
	"author"			TEXT,
	"booktitle"			TEXT,
	"chapter"			TEXT,
	"crossref"			TEXT,
	"edition"			TEXT,
	"editor"			TEXT,
	"eprint"			TEXT,
	"howpublished"		TEXT,
	"institution"		TEXT,
	"journal"			TEXT,
	"key"				TEXT,
	"month"				TEXT,
	"note"				TEXT,
	"number"			TEXT,
	"organization"		TEXT,
	"pages"				TEXT,
	"publisher"			TEXT,
	"school"			TEXT,
	"series"			TEXT,
	"title"				TEXT,
	"type"				TEXT,
	"url"				TEXT,
	"volume"			TEXT,
	"year"				TEXT,
	"publicationType"	TEXT,
	"entryKey"			TEXT
);
